### ISSUE TITLE
目前作者还在更新吗？

### ISSUE THREAD

**Issue by Micro66** [origingroup/hydrogen#48]

**Comment by yuyandong** [comment]
看起来是，希望他继续更新

**Comment by 6174** [comment]
非常抱歉，换了工作，短期内业余时间已被榨干了，不过这个是长期的事儿，会一直持续思考和计划

**Comment by yuyandong** [comment]
CredentialPrompt for cred.sshInfoTypes.invalid not handled Error: CredentialPrompt for cred.sshInfoTypes.invalid not handled at file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:28576 at o (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/vendor/react/vendors.js:25:2127371) at Generator._invoke (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/vendor/react/vendors.js:25:2128510) at Generator.e.(anonymous function) [as next] (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/vendor/react/vendors.js:25:2127550) at o (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:27120) at file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:27266 at Promise (<anonymous>) at file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:27064 at e (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:27684) at p (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:20466) at c (file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:21365) at file:///Applications/Hydrogen.app/Contents/Resources/app.asar/dist/bundle.js:1:21551 at <anonymous> at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by Xmader** [comment]
我帮原作者移植到了 Windows 和 Linux 操作系统上
[Hydrogen for Linux & Windows](https://github.com/Xmader/hydrogen)

**Comment by yuyandong** [comment]
你帮他更新下Mac 版吧，bug 导致 push 不了

**Comment by Xmader** [comment]
出现这种错误一般是因为你没有正确配置SSH公钥和私钥, 作者应该加上更人性化的提示

**Comment by Xmader** [comment]
[MacOS 版已更新](https://github.com/Xmader/hydrogen/tree/darwin), 不过我没有Mac, 没办法测试

**Comment by yuyandong** [comment]
Mac  10.13.5 系统打不开新版
![image](https://user-images.githubusercontent.com/11476857/42407612-60b6c10a-81f2-11e8-8611-f654120ab8bc.png)

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Hydrogen.app/Contents/MacOS/Hydrogen
  Reason: no suitable image found.  Did find:
	/Applications/Hydrogen.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/Hydrogen.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10cf03000 -        0x10cf03ff7 +org.origingroup.Hydrogen (1.1.10 - 1.1.10) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /Applications/Hydrogen.app/Contents/MacOS/Hydrogen
       0x11bd01000 -        0x11bd4b9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld

**Comment by yuyandong** [comment]
谢谢 Xmader，我更正了1.1.10 版本里面的公用钥匙，能 push 了。

**Comment by Xmader** [comment]
现在1.2.1版的bug已修复, 可以正常使用了

**Comment by goodteaio** [comment]
这个是开源的吗？
